-- Seed T-shirt Regular colors with catalogue images.
-- Images stored at products/tshirt-regular/{filename} in the product-media bucket.

DELETE FROM public.product_colors WHERE product_id = 'tshirt-regular';

INSERT INTO public.product_colors (product_id, name, hex, image_url, image_urls) VALUES
('tshirt-regular', 'أوبرجين',   '#742e4c', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-aubergine-742e4c-m.jpg',   ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-aubergine-742e4c-m.jpg']),
('tshirt-regular', 'بيج فاتح',  '#cfc9be', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-beige_clair-cfc9be-m.jpg', ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-beige_clair-cfc9be-m.jpg']),
('tshirt-regular', 'بيج غامق',  '#cec6a5', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-beige_fonce-cec6a5-m.jpg', ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-beige_fonce-cec6a5-m.jpg']),
('tshirt-regular', 'أبيض',      '#ffffff', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-blanc-ffffff-m.jpg',           ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-blanc-ffffff-m.jpg']),
('tshirt-regular', 'أزرق سماوي','#a2d1f0', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-bleu_ciel-a2d1f0-m.jpg',        ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-bleu_ciel-a2d1f0-m.jpg']),
('tshirt-regular', 'أزرق ليلي', '#28355d', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-bleu_nuit-28355d-m.jpg',      ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-bleu_nuit-28355d-m.jpg']),
('tshirt-regular', 'أزرق ملكي غامق', '#273ac9', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-bleu_roi_fonce-273ac9-m.jpg', ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-bleu_roi_fonce-273ac9-m.jpg']),
('tshirt-regular', 'أزرق مخضر', '#8dd9de', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-bleu_vert-8dd9de-m.jpg',       ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-bleu_vert-8dd9de-m.jpg']),
('tshirt-regular', 'رمادي فاتح','#d4dee1', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-gris_clair-d4dee1-m.jpg',      ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-gris_clair-d4dee1-m.jpg']),
('tshirt-regular', 'رمادي غامق','#7a828e', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-gris_fonce-7a828e-m.jpg',      ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-gris_fonce-7a828e-m.jpg']),
('tshirt-regular', 'أصفر خردلي','#dfc344', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-jaune_moutarde-dfc344-m.jpg',  ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-jaune_moutarde-dfc344-m.jpg']),
('tshirt-regular', 'بني',        '#78615e', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-marron-78615e-m.jpg',          ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-marron-78615e-m.jpg']),
('tshirt-regular', 'أسود',      '#000000', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-noir-000000-m.png',           ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-noir-000000-m.png']),
('tshirt-regular', 'وردي فاتح','#e3c5cd',  'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-rose_clair-e3c5cd-m.jpg',      ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-rose_clair-e3c5cd-m.jpg']),
('tshirt-regular', 'وردي فوشيا','#b62d6b', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-rose_fuschia-b62d6b-m.jpg',    ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-rose_fuschia-b62d6b-m.jpg']),
('tshirt-regular', 'أحمر',      '#b52944', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-rouge-b52944-m.jpg',           ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-rouge-b52944-m.jpg']),
('tshirt-regular', 'سلمون',     '#dd9e82', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-saumon-dd9e82-m.png',          ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-saumon-dd9e82-m.png']),
('tshirt-regular', 'أخضر زجاجي','#6b9d95', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-vert_bouteille-6b9d95-m.jpg',   ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-vert_bouteille-6b9d95-m.jpg']),
('tshirt-regular', 'أخضر كاكي', '#888c6b', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-vert_kaki-888c6b-m.jpg',      ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-vert_kaki-888c6b-m.jpg']),
('tshirt-regular', 'أخضر باسبورت','#426c52', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-vert_passport-426c52-m.jpg', ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-vert_passport-426c52-m.jpg']),
('tshirt-regular', 'بنفسجي',    '#5a3eb4', 'https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-violet-5a3eb4-m.jpg',        ARRAY['https://wjzkhgizatmovwudqwgf.supabase.co/storage/v1/object/public/product-media/products/tshirt-regular/t_shirt_regular-violet-5a3eb4-m.jpg']);
